CREATE TRIGGER ManyComplaints ON POTENTIAL_PROBLEMS
AFTER INSERT
AS

BEGIN
	
	PRINT 'Maybe you should just be grateful.'
END
GO
INSERT INTO POTENTIAL_PROBLEMS VALUES (11,  '1xjio43twpl809604', 55, 14381);